### ISSUE TITLE
下载了固件发现内核时6.x的不是5.15的

### ISSUE THREAD

**Issue by poctopus** [popeyema/OpenWrt-FastRhino-r68s-r66s#4]
今天下载了一个最新版本，发现标注时5.15的内核，可是刷入tf卡后，上机后发现是6.x的。

楼主看看脚本哪里有问题。

**Comment by poctopus** [comment]
问题解决了。是源文件那里默认把5.15和6.1都打开了，需要调整diy脚本就可以了。

**Comment by popeyema** [comment]
解决就好
